/*
 * Copyright 2022-2026 Michael Büchner, Deutsche Digitale Bibliothek
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.ddb.labs.ddbid.cronjob.objects;

import de.ddb.labs.ddbid.cronjob.helper.Helper;
import de.ddb.labs.ddbid.database.Database;
import de.ddb.labs.ddbid.model.Type;
import de.ddb.labs.ddbid.service.ItemService;
import de.ddb.labs.ddbid.service.OrganizationService;
import de.ddb.labs.ddbid.service.PersonService;
import de.ddb.labs.ddbid.service.StatisticsService;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.Iterator;
import java.util.Set;
import java.util.zip.GZIPInputStream;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Slf4j
@Service
@RequiredArgsConstructor
public class Import implements Runnable {

    private static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZ").withZone(ZoneId.systemDefault());
    private static final CSVFormat CSV_WITH_FIRST_RECORD_AS_HEADER = CSVFormat.DEFAULT.builder()
            .setHeader()
            .setSkipHeaderRecord(true)
            .get();
    // private final static String CREATE_SCHEMA = "CREATE SCHEMA IF NOT EXISTS \"main\";";
    
    private final static String DROP_ITEM_TABLE = """
                                                  DROP TABLE IF EXISTS "item";
                                                  DROP INDEX IF EXISTS "item_timestamp";
                                                  DROP INDEX IF EXISTS "item_status";
                                                  """;
    private final static String DROP_PERSON_TABLE = """
                                                    DROP TABLE IF EXISTS "person";
                                                    DROP INDEX IF EXISTS "person_timestamp";
                                                    DROP INDEX IF EXISTS "person_status";
                                                    """;
    private final static String DROP_ORGANIZATION_TABLE = """
                                                          DROP TABLE IF EXISTS "organization";
                                                          DROP INDEX IF EXISTS "organization_timestamp";
                                                          DROP INDEX IF EXISTS "organization_status";
                                                          """;
    private final static String CREATE_ITEM_TABLE = """
                                                    CREATE TABLE IF NOT EXISTS "item"(
                                                      "pkey" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                      "timestamp" TIMESTAMP NOT NULL,
                                                      "id" VARCHAR(32) NOT NULL,
                                                      "status" VARCHAR(16) NOT NULL,
                                                      "dataset_id" VARCHAR(128),
                                                      "label" VARCHAR(1024),
                                                      "provider_id" VARCHAR(256),
                                                      "supplier_id" VARCHAR(128),
                                                      "provider_item_id" VARCHAR(512),
                                                      "sector_fct" VARCHAR(16),
                                                      PRIMARY KEY ("pkey")
                                                    );
                                                    """;

    private final static String CREATE_PERSON_TABLE = """
                                                      CREATE TABLE IF NOT EXISTS "person"(
                                                        "pkey" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                        "timestamp" TIMESTAMP NOT NULL,
                                                        "id" VARCHAR(64) NOT NULL,
                                                        "status" VARCHAR(16) NOT NULL,
                                                        "variant_id" VARCHAR(256),
                                                        "preferredName" VARCHAR(1024),
                                                        "type" VARCHAR(32),
                                                        PRIMARY KEY ("pkey")
                                                      );
                                                      """;

    private final static String CREATE_ORGANIZATION_TABLE = """
                                                            CREATE TABLE IF NOT EXISTS "organization"(
                                                              "pkey" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                              "timestamp" TIMESTAMP NOT NULL,
                                                              "id" VARCHAR(64) NOT NULL,
                                                              "status" VARCHAR(16) NOT NULL,
                                                              "variant_id" VARCHAR(256),
                                                              "preferredName" VARCHAR(1024),
                                                              "type" VARCHAR(32),
                                                              PRIMARY KEY ("pkey")
                                                            );
                                                            """;

    private final static String CREATE_INDEXES = """
                                                  CREATE INDEX IF NOT EXISTS "item_timestamp" ON "item"("timestamp");
                                                  CREATE INDEX IF NOT EXISTS "item_status" ON "item"("status");
                                                  CREATE INDEX IF NOT EXISTS "item_status_timestamp" ON "item"("status", "timestamp");
                                                  CREATE INDEX IF NOT EXISTS "item_status_provider" ON "item"("status", "provider_id");
                                                  CREATE INDEX IF NOT EXISTS "item_status_sector" ON "item"("status", "sector_fct");
                                                  CREATE INDEX IF NOT EXISTS "item_filter_id" ON "item"("status", "timestamp", "id");
                                                  CREATE INDEX IF NOT EXISTS "item_filter_provider_item" ON "item"("status", "timestamp", "provider_item_id");
                                                  CREATE INDEX IF NOT EXISTS "item_filter_dataset" ON "item"("status", "timestamp", "dataset_id");
                                                  CREATE INDEX IF NOT EXISTS "item_filter_provider" ON "item"("status", "timestamp", "provider_id");
                                                  CREATE INDEX IF NOT EXISTS "item_filter_sector" ON "item"("status", "timestamp", "sector_fct");
                                                  CREATE INDEX IF NOT EXISTS "item_filter_supplier" ON "item"("status", "timestamp", "supplier_id");
                                                  CREATE INDEX IF NOT EXISTS "person_timestamp" ON "person"("timestamp");
                                                  CREATE INDEX IF NOT EXISTS "person_status" ON "person"("status");
                                                  CREATE INDEX IF NOT EXISTS "person_status_timestamp" ON "person"("status", "timestamp");
                                                  CREATE INDEX IF NOT EXISTS "person_filter_id" ON "person"("status", "timestamp", "id");
                                                  CREATE INDEX IF NOT EXISTS "person_filter_variant" ON "person"("status", "timestamp", "variant_id");
                                                  CREATE INDEX IF NOT EXISTS "person_filter_type" ON "person"("status", "timestamp", "type");
                                                  CREATE INDEX IF NOT EXISTS "organization_timestamp" ON "organization"("timestamp");
                                                  CREATE INDEX IF NOT EXISTS "organization_status" ON "organization"("status");
                                                  CREATE INDEX IF NOT EXISTS "organization_status_timestamp" ON "organization"("status", "timestamp");
                                                  CREATE INDEX IF NOT EXISTS "organization_filter_id" ON "organization"("status", "timestamp", "id");
                                                  CREATE INDEX IF NOT EXISTS "organization_filter_variant" ON "organization"("status", "timestamp", "variant_id");
                                                  CREATE INDEX IF NOT EXISTS "organization_filter_type" ON "organization"("status", "timestamp", "type");
                                                  """;

    private final static String INSERT_ITEM = """
                                               INSERT INTO "item"("timestamp","id","status","provider_item_id","dataset_id","label","provider_id","sector_fct","supplier_id")
                                               VALUES (?,?,?,?,?,?,?,?,?);
                                               """;

    private final static String INSERT_PERSON = """
                                                 INSERT INTO "person"("timestamp","id","status","variant_id","preferredName","type")
                                                 VALUES (?,?,?,?,?,?);
                                                 """;

    private final static String INSERT_ORGANIZATION = """
                                                       INSERT INTO "organization"("timestamp","id","status","variant_id","preferredName","type")
                                                       VALUES (?,?,?,?,?,?);
                                                       """;

    private final Database database;
    private final StatisticsService statisticsService;
    private final ItemService itemService;
    private final PersonService personService;
    private final OrganizationService organizationService;

    @Value("${ddbid.datapath.item}")
    private String dataPathItem;

    @Value("${ddbid.datapath.person}")
    private String dataPathPerson;

    @Value("${ddbid.datapath.organization}")
    private String dataPathOrganization;

    @Override
    public void run() {
        try {
            importToDb();
        } catch (Exception ex) {
            log.error(ex.getMessage());
        }
    }

    public void importToDb() throws IOException, SQLException {

        // database.getJdbcTemplate().execute(CREATE_SCHEMA); // create database (only inital)
        database.getJdbcTemplate().execute(DROP_ITEM_TABLE); // drop existing tables
        database.getJdbcTemplate().execute(DROP_PERSON_TABLE);
        database.getJdbcTemplate().execute(DROP_ORGANIZATION_TABLE);
        database.getJdbcTemplate().execute(CREATE_ITEM_TABLE); // create table
        database.getJdbcTemplate().execute(CREATE_PERSON_TABLE);
        database.getJdbcTemplate().execute(CREATE_ORGANIZATION_TABLE);

        for (Type t : Type.values()) {
            switch (t) {
                case ITEM ->
                    importTypes(t, dataPathItem);
                case PERSON ->
                    importTypes(t, dataPathPerson);
                case ORGANIZATION ->
                    importTypes(t, dataPathOrganization);
                default -> {
                }
            }

        }
        database.getJdbcTemplate().execute(CREATE_INDEXES);
        if (database.isPostgres()) {
            statisticsService.ensureDatabaseIndexes();
        }
        statisticsService.clearCache();
        itemService.clearTimestampCache();
        personService.clearTimestampCache();
        organizationService.clearTimestampCache();

    }

    private void importTypes(Type type, String dataPath) throws IOException, SQLException {
        final Set<File> filesItem = Helper.getOkCmpFiles(dataPath, Comparator.naturalOrder());

        for (File f : filesItem) {
            try (final InputStream fileStream = new FileInputStream(f); final InputStream gzipStream = new GZIPInputStream(fileStream); final InputStreamReader decoder = new InputStreamReader(gzipStream, StandardCharsets.UTF_8); final BufferedReader br = new BufferedReader(decoder)) {

                final CSVParser records = CSV_WITH_FIRST_RECORD_AS_HEADER.parse(br);
                final Iterator<CSVRecord> recIt = records.iterator();
                validateHeader(type, records.getHeaderNames());
                final String recQuery = insertQuery(type);

                try (Connection connection = database.getConnection(); PreparedStatement statement = connection.prepareStatement(recQuery)) {
//                PreparedStatementCreator psc = new PreparedStatementCreator() {
//                    @Override
//                    public PreparedStatement createPreparedStatement(Connection con) throws SQLException {
//                        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//                    }
//                }
//                        
                    int count = 0;
                    while (recIt.hasNext()) {
                        final CSVRecord rec = recIt.next();
                        final LocalDateTime localDateTime = LocalDateTime.from(dtf.parse(rec.get("timestamp")));
                        statement.setTimestamp(1, Timestamp.valueOf(localDateTime));
                        statement.setString(2, StringUtils.abbreviate(rec.get("id"), 32)); // id VARCHAR(32) NOT NULL,
                        statement.setString(3, StringUtils.abbreviate(rec.get("status"), 16)); // status VARCHAR(16) NOT NULL,
                        switch (type) {
                            case ITEM -> {
                                statement.setString(4, StringUtils.abbreviate(rec.get("provider_item_id"), 512));
                                statement.setString(5, StringUtils.abbreviate(rec.get("dataset_id"), 128));
                                statement.setString(6, StringUtils.abbreviate(rec.get("label"), 1024));
                                statement.setString(7, StringUtils.abbreviate(rec.get("provider_id"), 256));
                                statement.setString(8, StringUtils.abbreviate(rec.get("sector_fct"), 16));
                                statement.setString(9, StringUtils.abbreviate(rec.get("supplier_id"), 128));
                            }
                            case PERSON -> {
                                statement.setString(4, StringUtils.abbreviate(rec.get("variant_id"), 256));
                                statement.setString(5, StringUtils.abbreviate(rec.get("preferredName"), 1024));
                                statement.setString(6, StringUtils.abbreviate(rec.get("type"), 32));
                            }
                            case ORGANIZATION -> {
                                statement.setString(4, StringUtils.abbreviate(rec.get("variant_id"), 256));
                                statement.setString(5, StringUtils.abbreviate(rec.get("preferredName"), 1024));
                                statement.setString(6, StringUtils.abbreviate(rec.get("type"), 32));
                            }
                            default -> {
                            }
                        }
                        statement.addBatch();

                        if (++count % 1000 == 0 || !recIt.hasNext()) {
                            statement.executeBatch();
                        }
                    }
                    connection.commit();
                    log.info("Copied {} MISSING {} from {} to database with \"{}\"", count, type, f.getName(), recQuery.toString());
                } catch (SQLException ex) {
                    log.warn("Could not import {} from {}. {}", type, f.getName(), ex.getMessage());
                    throw ex;
                }
            }
        }
    }

    private static String insertQuery(Type type) {
        return switch (type) {
            case ITEM -> INSERT_ITEM;
            case PERSON -> INSERT_PERSON;
            case ORGANIZATION -> INSERT_ORGANIZATION;
            default -> throw new IllegalArgumentException("Unsupported type: " + type);
        };
    }

    private static void validateHeader(Type type, Iterable<String> headerNames) {
        final Set<String> headers = new java.util.HashSet<>();
        for (String header : headerNames) {
            headers.add(header);
        }

        final Set<String> expected = switch (type) {
            case ITEM -> Set.of("timestamp", "id", "status", "provider_item_id", "dataset_id", "label", "provider_id", "sector_fct", "supplier_id");
            case PERSON, ORGANIZATION -> Set.of("timestamp", "id", "status", "variant_id", "preferredName", "type");
            default -> throw new IllegalArgumentException("Unsupported type: " + type);
        };
        if (!headers.containsAll(expected)) {
            throw new IllegalArgumentException("CSV header for " + type + " does not contain expected fields " + expected);
        }
    }
}
